package database;

public class TableNames {
    public final static String
            brandTable = "brands",

    //Transmission
            hydPumpMotionTypesTable = "hyd_pumps_motion_types",
            hydMotorMotionTypesTable = "hyd_mot_motion_types",
            planetReductorTypesTable = "planet_reductor_types",
            pumpReductorTypesTable = "pump_reductor_types",
            hydPumpMotionTable = "hyd_pumps_motion",
            hydMotorMotionTable = "hyd_mot_motion",
            planetReductorTable = "planet_reductor",
            pumpReductorTable = "pump_reductor",
            transmissionTable = "transmission",
    //Disel
            diselTypesTable = "disel_types",
            diselEngines = "dvs",
            disel = "disel",
    //Coolant system
            coolantSystem = "coolant_system",
            coolantSysDocTable = "coolant_system_docs",
            waterCoolerDvsTable = "water_cooler_dvs",
            oilCoolDvsTable = "oil_cooler_dvs",
            oilCoolHstTable = "oil_cooler_hst",
            airCondCoolTable = "air_cond_cooler",
            wingTable = "wing",
            wingDriveTable = "wing_drive",
            impellerTable = "impeller_types",
            preHeaterTypeTable = "pre_heater_types",
            preHeaterTable = "pre_heater",
    //Attachments
            attachmentsTable = "attachments",
            attachPumpTypesTable = "attach_pump_types",
            attachPumpTable = "attach_pump",
            fanPumpTypesTable = "fan_pump_types",
            fanPumpTable = "fan_pump",
            fanMotorTypesTable = "fan_mot_types",
            fanMotorTable = "fan_motor",
            extraAttachPumpTable = "extra_attach_pump",
            extraAttachMotorTable = "extra_attach_motor",
            hydDistributorTypeTable = "hyd_distributor_types",
            hydDustributorTable = "hyd_distributor",
            hydCylindersTable = "hyd_cylinders",
            hydCylinderTypesTable = "hyd_cyl_otv_lift",
            hydLockSkewTable = "hyd_lock_skew",
            frontAttachmentsTable = "front_attach_type",
            backAttachmentsTable = "back_attach_type",
            winchTable = "winch",
    //Bogies
            bogiesTable = "bogies",
            bogiesTypesTable = "bogies_types",
            oneFlangeRollersTable = "one_flange_rollers",
            twoFlangeRollersTable = "two_flange_rollers",
            pullOnWheelTable = "pull_on_wheel_types",
            leaderWheelTable = "leader_wheel_types",
            caterpillarTypesTable = "caterpillar_types",
            caterBrandTable = "cater_brand",
            caterWidthTable = "cater_width",
            grouserQuantTable = "grouser_quant",
            jointHingeTable = "joint_hinge",
            caterStepTable = "cater_step",
    //Cabin
            cabinTable = "cabin",
            cabinDocTable = "cabin_type",
            airConditionerTable = "air_conditioner",
            airHeaterTable = "air_heater",
            fvuTable = "filt_vent_set",
            radioPlayerTable = "radio_player",
            ropsTable = "rops",
            antivandLatticeTable = "antivandal_lattice",
    //Electrics
            electricsTable = "electrics",
            motionJoyTable = "motion_joystick",
            attachJoyTable = "attach_joystick",
            controllerTable = "controller",
            lightersTable = "lighters",
            batteryTable = "battery",
            controllerTypesTable = "controller_types",
            softwareTable = "software_ver";
}
